model_configs:
  checkpoint_path: null
  esm_model_name: facebook/esm2_t33_650M_UR50D
  protein_model_name_or_path: facebook/esm2_t33_650M_UR50D
  proteina_model_name_or_path: facebook/esm2_t33_650M_UR50D
  model_hyperparameters:
    learning_rate: 0.001
    warmup_steps_ratio: 0.06
    protein_max_seq_len: 2048
    proteina_max_seq_len: 2048
    gradient_accumulation_steps: 32
    projected_size: 256
    projected_dropout: 0.3
    esm_layer: 33
    mean_pool: true
  protein_fine_tuning_type: projection
  proteina_fine_tuning_type: projection
  loss_function: cosine_mse
  pkd_lower_bound: 4.0
  pkd_upper_bound: 10.0

dataset_configs:
  dataset_name: SYK
  split_method: random
  harmonize_affinities_mode: null

training_configs:
  random_seed: 1234
  device: 0
  patience: 75
  epochs: 150
  batch_size: 8
  outputs_dir: "outputs"